console.log(Math.E)
console.log(Math.PI)
var n=4.589
console.log(Math.abs(n))
console.log(Math.floor(n))
console.log(Math.round(n))
console.log(Math.max(400,500))
console.log(Math.min(400,500,990))
console.log(Math.pow(2,3))
console.log(Math.sqrt(9))
console.log(Math.random())
console.log(Math.random() * 50+1)
console.log(round(Math.random()*50+1))
